///usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS com.google.code.gson:gson:2.10.1

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * ExportUtils - Export standup reports in various formats
 *
 * Usage: jbang ExportUtils.java <format> <report> <username> <days> [output-file]
 */
public class ExportUtils {

    private static final Gson gson = new GsonBuilder().setPrettyPrinting().create();

    public static String exportMarkdown(String report, String username, int days, int activityCount) {
        LocalDateTime now = LocalDateTime.now();
        String timestamp = now.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        StringBuilder md = new StringBuilder();
        md.append("# Standup Report\n\n");
        md.append("**Generated**: ").append(timestamp).append("\n");
        md.append("**User**: ").append(username).append("\n");
        md.append("**Period**: ").append(days).append(" day").append(days > 1 ? "s" : "").append("\n");
        md.append("**Activity Count**: ").append(activityCount).append("\n\n");
        md.append("---\n\n");
        md.append(report).append("\n\n");
        md.append("---\n\n");
        md.append("*Generated by claude-gh-standup*\n");

        return md.toString();
    }

    public static String exportJSON(String report, String username, int days, int activityCount) {
        LocalDateTime now = LocalDateTime.now();
        String timestamp = now.format(DateTimeFormatter.ISO_DATE_TIME);

        JsonObject output = new JsonObject();

        JsonObject metadata = new JsonObject();
        metadata.addProperty("generated_at", timestamp);
        metadata.addProperty("user", username);
        metadata.addProperty("days", days);
        metadata.addProperty("activity_count", activityCount);

        output.add("metadata", metadata);
        output.addProperty("report", report);

        return gson.toJson(output);
    }

    public static String exportHTML(String report, String username, int days, int activityCount) {
        LocalDateTime now = LocalDateTime.now();
        String timestamp = now.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n");
        html.append("<html>\n");
        html.append("<head>\n");
        html.append("    <meta charset=\"UTF-8\">\n");
        html.append("    <title>Standup Report - ").append(username).append("</title>\n");
        html.append("    <style>\n");
        html.append("        body {\n");
        html.append("            font-family: Arial, sans-serif;\n");
        html.append("            max-width: 800px;\n");
        html.append("            margin: 40px auto;\n");
        html.append("            padding: 20px;\n");
        html.append("            line-height: 1.6;\n");
        html.append("        }\n");
        html.append("        h1 {\n");
        html.append("            color: #333;\n");
        html.append("            border-bottom: 2px solid #333;\n");
        html.append("            padding-bottom: 10px;\n");
        html.append("        }\n");
        html.append("        .metadata {\n");
        html.append("            background-color: #f5f5f5;\n");
        html.append("            padding: 15px;\n");
        html.append("            border-radius: 5px;\n");
        html.append("            margin-bottom: 20px;\n");
        html.append("            color: #666;\n");
        html.append("            font-size: 0.9em;\n");
        html.append("        }\n");
        html.append("        .report {\n");
        html.append("            line-height: 1.8;\n");
        html.append("        }\n");
        html.append("        .footer {\n");
        html.append("            margin-top: 40px;\n");
        html.append("            padding-top: 20px;\n");
        html.append("            border-top: 1px solid #ddd;\n");
        html.append("            color: #999;\n");
        html.append("            font-size: 0.85em;\n");
        html.append("            text-align: center;\n");
        html.append("        }\n");
        html.append("    </style>\n");
        html.append("</head>\n");
        html.append("<body>\n");
        html.append("    <h1>Standup Report</h1>\n");
        html.append("    <div class=\"metadata\">\n");
        html.append("        <p><strong>Generated:</strong> ").append(timestamp).append("</p>\n");
        html.append("        <p><strong>User:</strong> ").append(username).append("</p>\n");
        html.append("        <p><strong>Period:</strong> ").append(days).append(" day").append(days > 1 ? "s" : "").append("</p>\n");
        html.append("        <p><strong>Activity Count:</strong> ").append(activityCount).append("</p>\n");
        html.append("    </div>\n");
        html.append("    <div class=\"report\">\n");
        html.append("        ").append(report.replace("\n", "<br>\n        ")).append("\n");
        html.append("    </div>\n");
        html.append("    <div class=\"footer\">\n");
        html.append("        <p>Generated by claude-gh-standup</p>\n");
        html.append("    </div>\n");
        html.append("</body>\n");
        html.append("</html>\n");

        return html.toString();
    }

    public static void writeToFile(String content, String filePath) throws IOException {
        Path path = Paths.get(filePath);

        // Create parent directories if needed
        Path parent = path.getParent();
        if (parent != null && !Files.exists(parent)) {
            Files.createDirectories(parent);
        }

        Files.writeString(path, content);
        System.err.println("Report saved to " + filePath);
    }

    public static void main(String... args) {
        try {
            if (args.length < 4) {
                System.err.println("Usage: jbang ExportUtils.java <format> <report> <username> <days> [output-file]");
                System.exit(1);
            }

            String format = args[0].toLowerCase();
            String report = args[1];
            String username = args[2];
            int days = Integer.parseInt(args[3]);
            String outputFile = args.length > 4 ? args[4] : null;

            // Assume activity count = 0 for now (can be passed as parameter if needed)
            int activityCount = 0;

            String output;
            switch (format) {
                case "markdown":
                    output = exportMarkdown(report, username, days, activityCount);
                    break;
                case "json":
                    output = exportJSON(report, username, days, activityCount);
                    break;
                case "html":
                    output = exportHTML(report, username, days, activityCount);
                    break;
                default:
                    System.err.println("Error: Invalid format '" + format + "'. Valid formats: markdown, json, html");
                    System.exit(1);
                    return;
            }

            if (outputFile != null) {
                writeToFile(output, outputFile);
            } else {
                System.out.println(output);
            }

        } catch (NumberFormatException e) {
            System.err.println("Error: days must be a valid integer");
            System.exit(1);
        } catch (Exception e) {
            System.err.println("Error exporting report: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
}
